export default [
  {
    imageUrl:
      "https://www.apple.com/newsroom/images/product/iphone/standard/Apple_iphone13_hero_09142021_inline.jpg.large.jpg",
    product: "iPhone 13",
    price_per_day: "₹86",
    emi_starting_from: "₹2578",
    emi_terms: "0/0/18",
    instant_discount: "₹1000",
    exchange_bonus: "₹6000",
    banks: [
      "Bajaj Finserv",
      "HDFC Bank",
      "HDB Financial Services",
      "IDFC First Bank",
      "ICICI Bank",
      "TVS Credit",
      "SBI Card",
      "Kotak Mahindra Bank",
    ],
    terms_and_conditions: "T&C Apply",
  },
  {
    imageUrl:
      "https://swapphone.nl/wp-content/uploads/2024/05/iPhone-14-Geel-6-600x600-1.webp",
    product: "iPhone 14",
    price_per_day: "₹101",
    emi_starting_from: "₹3050",
    emi_terms: "0/0/18",
    instant_discount: "₹1000",
    exchange_bonus: "₹6000",
    banks: ["SBI Card", "ICICI Bank"],
    terms_and_conditions: "T&C Apply",
  },
  {
    imageUrl:
      "https://www.imagineonline.store/cdn/shop/files/iPhone_15_Blue_PDP_Image_Position-1__en-IN.jpg",
    product: "iPhone 15",
    price_per_day: "₹90",
    emi_starting_from: "₹2704",
    emi_terms: "0/0/24",
    instant_discount: "₹3000",
    exchange_bonus: "₹6000",
    banks: ["Various banks and financial institutions"],
    terms_and_conditions: "T&C Apply",
  },
  {
    imageUrl:
      "https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/iphone-16-finish-select-202409-6-1inch-white?wid=5120&hei=2880&fmt=webp&qlt=70&.v=UXp1U3VDY3IyR1hNdHZwdFdOLzg1V0tFK1lhSCtYSGRqMUdhR284NTN4OWhabGVFdVhnaExpMWhzbVh0SzhIT09MekhWSGZtV1pvV240QzNuTk80VXhseHVZcEw1SmhqcElaQkJMTm9FMytjRGRjd0V1bkY3a0xXbUtlY3VlTmc&traceId=1",
    product: "iPhone 16",
    price_per_day: "₹104",
    emi_starting_from: "₹3121",
    emi_terms: "0/0/24",
    instant_discount: "₹4000",
    exchange_bonus: "₹6000",
    banks: [
      "Bajaj Finserv",
      "HDFC Bank",
      "HDB Financial Services",
      "IDFC First Bank",
      "ICICI Bank",
      "TVS Credit",
      "SBI Card",
      "Kotak Mahindra Bank",
    ],
    terms_and_conditions: "T&C Apply",
  },
  {
    imageUrl:
      "https://s3.zoommer.ge/site/6f921931-689a-4313-b863-6bd6b620deac_Thumb.png",
    product: "iPhone 16 Plus",
    price_per_day: "₹118",
    emi_starting_from: "₹3538",
    emi_terms: "0/0/24",
    instant_discount: "₹4000",
    exchange_bonus: "₹6000",
    banks: [
      "Bajaj Finserv",
      "HDFC Bank",
      "HDB Financial Services",
      "IDFC First Bank",
      "ICICI Bank",
      "TVS Credit",
      "SBI Card",
      "Kotak",
    ],
    terms_and_conditions: "T&C Apply",
  },
  {
    imageUrl:
      "https://swapphone.nl/wp-content/uploads/2024/10/iPhone-16-Pro-Wit-Titanium-1-600x600-1.webp",
    product: "iPhone 16 Pro",
    tagline: "Built for Apple Intelligence.",
    offer: "Connect for new Offer.",
    cashback: "3000* Instant Cashback on",
    banks: ["SBI Card", "ICICI Bank", "Kotak"],
    image_description:
      "The image is an advertisement for the iPhone 16 Pro, featuring four different color variants of the phone. The advertisement is themed around New Year celebrations, with fireworks in the background. It highlights a special offer of 3000 instant cashback available through SBI Card, ICICI Bank, and Kotak.",
  },
];
